### ISSUE TITLE
close button

### ISSUE THREAD

**Issue by atmanegara** [hoaaah/yii2-startbootstrap-sb-admin-2-asset#1]
selalu muncul close button di setiap page, baik page login atau lainnya, gimana yaa cara hilangkannya?

![image](https://user-images.githubusercontent.com/9096711/88468041-9dacdf00-cf10-11ea-943b-0ca2df02f020.png)

**Comment by hoaaah** [comment]
Alert widget sudah Bootstrap 4?

**Comment by atmanegara** [comment]
> Alert widget sudah Bootstrap 4?

default dari punya mas, udah bootstrap 4 alertnya, udah saya instal juga BS4 nya

**Comment by hoaaah** [comment]
Sorry, fix at https://github.com/hoaaah/yii2-startbootstrap-sb-admin-2-asset/commit/98cef018f189d20c39f966b96c822ec9ae5e69d4
